fix regression: FSM_INITIAL_STATE: define template specialization in "namespace tinyfsm" block
Due to a bug, gcc < 7.0 (tested with 5.4.0, 6.4.0) fails with:

    error: specialization of ‘template<class F> static void tinyfsm::Fsm<F>::set_initial_state()’ in different namespace [-fpermissive]

Fixed by defining template specialization in "namespace tinyfsm"
block, which should work for all versions of gcc.

Tested with: gcc-6.4.0, gcc-7.3.0, clang-6.0.0

See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56480

Regression from commit: cf4a7467daf95c00c0526030f51f7947f6edac0b